name: brick_breaker
description: "Re-implementing Woz's Breakout"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  flame_audio: ^2.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/audio/background_music.mp3
    - assets/audio/brick_hit.mp3
    - assets/audio/paddle_hit.mp3 
    - assets/audio/game_over.mp3
    - assets/audio/you_win.mp3




